# fly.toml app configuration file generated for demo-pb-flyio on 2024-02-21T11:45:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-pb-flyio'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"